apiVersion : apps/v1
kind: Deployment
metadata:
  name: akannanspringbootapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akannanspringbootapp
  template:
    metadata:
      labels:
        app: akannanspringbootapp 
    spec:
      containers:
        - name: akannanspringbootapp 
          image: 639000616788.dkr.ecr.us-east-2.amazonaws.com/micro-service-eks:latest
          ports:
          - containerPort: 80
